---
- name: Set the timezone to Darwin
  win_timezone:
    timezone: AUS Central Standard Time

- name: Set sleep to never
  script: scripts/disable-sleep.bat

- name: Set hibernation to never
  script: scripts/disable-hibernation.bat

- name: Install RSAT Server Manager tool
  script: scripts/install-RSATServerManager.ps1

- name: Install necessary updates
  win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
    reboot: true

- name: Install preferred chocolatey software (no params)
  win_chocolatey:
    name:
      - firefox
      - vim
      - spotify
      - pwsh
    state: present

- name: Install Steam
  win_package:
    path: https://cdn.akamai.steamstatic.com/client/installer/SteamSetup.exe
    arguments: /S
    product_id: Steam
    state: present

- name: Create group for ssh users
  win_group:
    name: SSHUsers
    state: present
    description: Users of this group can ssh into the system

- name: Create local root user
  win_user:
    name: root
    state: present
    groups:
      - Administrators
      - SSHUsers

- name: Disable default Administrator user
  win_user:
    name: Administrator
    account_disabled: true

- name: Install Openssh
  win_chocolatey:
    name: openssh
    state: present
    package_params: /SSHServerFeature

- name: Copy ssh server config
  win_copy:
    src: configs/sshd_config
    dest: C:\ProgramData\ssh

- name: Add SSH keys to authorized key file
  win_lineinfile:
    path: C:\ProgramData\ssh\sshusers_authorized_keys
    state: present
    create: true
    line: "{{ lookup('url', 'https://github.com/megacorp-industries.keys', split_lines=False) }}"

- name: Copy PowerShell profile to host
  win_copy:
    src: configs/Microsoft.PowerShell_profile.ps1
    dest: C:\Users\{{ item }}\Documents\PowerShell
  loop: "{{ USERS }}"


