---
- name: Set the timezone to Darwin
  win_timezone:
    timezone: AUS Central Standard Time

- name: Set sleep to never
  script: files/scripts/disable-sleep.bat

- name: Set hibernation to never
  script: files/scripts/disable-hibernation.bat

- name: Install necessary updates
  win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
    reboot: true

- name: Install preferred chocolatey software (no params)
  win_chocolatey:
    name:
      - firefox
      - vim
      - spotify
      - pwsh
    state: present

- name: Install Openssh
  win_chocolatey:
    name: openssh
    state: present
    package_params: /SSHServerFeature

- name: Install Steam
  win_package:
    path: https://cdn.akamai.steamstatic.com/client/installer/SteamSetup.exe
    arguments: /S
    product_id: Steam
    state: present

- name: Create local root user
  win_user:
    name: root
    state: present
    groups:
      - Administrators

- name: Disable default Administrator user
  win_user:
    name: Administrator
    account_disabled: true

- name: Copy PowerShell profile to host
  win_copy:
    src: Microsoft.PowerShell_profile.ps1
    dest: C:\Users\{{ item }}\Documents\PowerShell
  loop: "{{ USERS }}"


